FORMAT: 1A
HOST: https://sandbox.codex.link/apid d

# Codex RESTful API
The Codex API is an extension to the Codex platform to get data from an organization's backend.
It includes collections per enabled module in Codex.
You can get a list of enabled modules using the /modules endpoint


## General Collection [/]


### Get API status [GET]
+ Response 200 (application/json)
        
        [
            { 
                "API INFO HERE":true
            }
        ]


## Modules Collection [/modules]
### Get all modules [GET]
+ Response 200 (application/json)
        
        [
            { 
                "internalName":"members"
            }
        ]



## Authenticatie [/authenticate]


### Genereer Authenticatie Token [POST]

Met deze call kan je een JWT (Javascript Web Token) genereren om de rest van de API te gebruiken.
Dit is dus identiek aan inloggen op een traditionele web applicatie.

+ Request
        + username (string) - Gebruikersnaam, doorgaans je e-mailadres
        + password (string) - Je wachtwoord
    
+ Response 200 (application/json)

        { 
            "token" : "12345"
        }





## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            

## members [/members]
### all [GET]

Description here

+ Response 200 (application/json)

### get [GET]

Description here

+ Response 200 (application/json)

### ids [GET]

Description here

+ Response 200 (application/json)

### query [GET]

Description here

+ Response 200 (application/json)

### filter [GET]

Description here

+ Response 200 (application/json)

### filterbatch [GET]

Description here

+ Response 200 (application/json)

### birthdays [GET]

Description here

+ Response 200 (application/json)

### fields [GET]

Description here

+ Response 200 (application/json)

### requestUpdateToken [GET]

Description here

+ Response 200 (application/json)

### traits [GET]

Description here

+ Response 200 (application/json)

## groups [/groups]